#source /usr/share/zsh/share/antigen.zsh
source /opt/homebrew/share/antigen/antigen.zsh
# source /usr/local/Cellar/antigen/2.2.3/share/antigen/antigen.zsh

# Set fzf installation directory
export FZF_BASE=/usr/local/opt/fzf

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle gitfast
# antigen bundle docker
antigen bundle fzf

export NVM_DIR="$HOME/.nvm"
export NVM_LAZY_LOAD=true
export NVM_COMPLETION=true
export NVM_NO_USE=true
# export NVM_AUTO_USE=true  # Auto load from .nvmrc
antigen bundle lukechilds/zsh-nvm

# Syntax highlighting bundle.
# antigen bundle zdharma/fast-syntax-highlighting

# Setting default user for agnoster theme
DEFAULT_USER="coditva"

# Load the theme.
antigen theme fishy

# Tell antigen that you're done.
antigen apply

# Setting up misc things
source ~/.dotfiles/zsh/misc.zsh

# Setting up aliases
source ~/.dotfiles/zsh/alias.zsh

source ~/.profile

# source ~/.dotfiles/fzf-gems/fzf_git_functions.sh
# source ~/.dotfiles/fzf-gems/fzf_git_keybindings.zsh

# Add iterm shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Change iterm profile from the command line
# iterm_profile() {
#     # ~/.dotfiles/iterm2/change_session_profile.py $1
#     ITERM_PROFILE=$1
# }
# iterm_toggle_profile() {
#     if [[ $ITERM_PROFILE == "Dark" ]]; then
#         iterm_profile Light
#     else
#         iterm_profile Dark
#     fi
# }

export FPATH="${FPATH}:${HOME}/.dotfiles/zsh/site-functions"

# Setting for the new UTF-8 terminal support
LC_CTYPE="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

# Added by Windsurf
# export PATH="/Users/coditva/.codeium/windsurf/bin:$PATH"

# Added by Antigravity
export PATH="/Users/coditva/.antigravity/antigravity/bin:$PATH"
